"""Tables Professor and Alunos

Revision ID: 8514992fc6dd
Revises: 
Create Date: 2023-06-05 00:09:37.129145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8514992fc6dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alunos',
    sa.Column('matricula', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=110), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=110), nullable=False),
    sa.Column('senha', sa.String(length=15), nullable=False),
    sa.Column('rua', sa.String(length=110), nullable=False),
    sa.Column('complemento', sa.String(length=110), nullable=True),
    sa.Column('cep', sa.String(length=12), nullable=False),
    sa.Column('bairro', sa.String(length=110), nullable=True),
    sa.PrimaryKeyConstraint('matricula'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Professor',
    sa.Column('matricula', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.String(length=110), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=110), nullable=False),
    sa.Column('senha', sa.String(length=15), nullable=False),
    sa.Column('rua', sa.String(length=110), nullable=False),
    sa.Column('complemento', sa.String(length=110), nullable=True),
    sa.Column('cep', sa.String(length=12), nullable=False),
    sa.Column('bairro', sa.String(length=110), nullable=True),
    sa.PrimaryKeyConstraint('matricula'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Professor')
    op.drop_table('Alunos')
    # ### end Alembic commands ###
